/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCPROJECT_H_RPCGEN
#define _RPCPROJECT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct User_array {
	struct {
		u_int userarray_len;
		int *userarray_val;
	} userarray;
	int userarray_size;
};
typedef struct User_array User_array;

struct max_min {
	int max;
	int min;
};
typedef struct max_min max_min;

struct multiplication {
	struct {
		u_int userarray_len;
		int *userarray_val;
	} userarray;
	int userarray_size;
	float multiplier;
};
typedef struct multiplication multiplication;

struct product_array {
	struct {
		u_int prodarr_len;
		float *prodarr_val;
	} prodarr;
};
typedef struct product_array product_array;

#define AVERAGE_PROG 0x23451111
#define AVERAGE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define average 1
extern  float * average_1(User_array *, CLIENT *);
extern  float * average_1_svc(User_array *, struct svc_req *);
extern int average_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define average 1
extern  float * average_1();
extern  float * average_1_svc();
extern int average_prog_1_freeresult ();
#endif /* K&R C */

#define MAXMIN_PROG 0x23451112
#define MAXMIN_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define maxmin 2
extern  max_min * maxmin_1(User_array *, CLIENT *);
extern  max_min * maxmin_1_svc(User_array *, struct svc_req *);
extern int maxmin_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define maxmin 2
extern  max_min * maxmin_1();
extern  max_min * maxmin_1_svc();
extern int maxmin_prog_1_freeresult ();
#endif /* K&R C */

#define PRODUCT_PROG 0x23451113
#define PRODUCT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define product 3
extern  product_array * product_1(multiplication *, CLIENT *);
extern  product_array * product_1_svc(multiplication *, struct svc_req *);
extern int product_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define product 3
extern  product_array * product_1();
extern  product_array * product_1_svc();
extern int product_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_User_array (XDR *, User_array*);
extern  bool_t xdr_max_min (XDR *, max_min*);
extern  bool_t xdr_multiplication (XDR *, multiplication*);
extern  bool_t xdr_product_array (XDR *, product_array*);

#else /* K&R C */
extern bool_t xdr_User_array ();
extern bool_t xdr_max_min ();
extern bool_t xdr_multiplication ();
extern bool_t xdr_product_array ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCPROJECT_H_RPCGEN */
