/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcproject.h"

bool_t
xdr_User_array (XDR *xdrs, User_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->userarray.userarray_val, (u_int *) &objp->userarray.userarray_len, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->userarray_size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_max_min (XDR *xdrs, max_min *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplication (XDR *xdrs, multiplication *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->userarray.userarray_val, (u_int *) &objp->userarray.userarray_len, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->userarray_size))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->multiplier))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_product_array (XDR *xdrs, product_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->prodarr.prodarr_val, (u_int *) &objp->prodarr.prodarr_len, 100,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
