/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcproject.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
average_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		User_array average_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case average:
		_xdr_argument = (xdrproc_t) xdr_User_array;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) average_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
maxmin_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		User_array maxmin_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case maxmin:
		_xdr_argument = (xdrproc_t) xdr_User_array;
		_xdr_result = (xdrproc_t) xdr_max_min;
		local = (char *(*)(char *, struct svc_req *)) maxmin_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
product_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		multiplication product_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case product:
		_xdr_argument = (xdrproc_t) xdr_multiplication;
		_xdr_result = (xdrproc_t) xdr_product_array;
		local = (char *(*)(char *, struct svc_req *)) product_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (AVERAGE_PROG, AVERAGE_VERS);
	pmap_unset (MAXMIN_PROG, MAXMIN_VERS);
	pmap_unset (PRODUCT_PROG, PRODUCT_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, AVERAGE_PROG, AVERAGE_VERS, average_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (AVERAGE_PROG, AVERAGE_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, MAXMIN_PROG, MAXMIN_VERS, maxmin_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MAXMIN_PROG, MAXMIN_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, PRODUCT_PROG, PRODUCT_VERS, product_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PRODUCT_PROG, PRODUCT_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, AVERAGE_PROG, AVERAGE_VERS, average_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (AVERAGE_PROG, AVERAGE_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, MAXMIN_PROG, MAXMIN_VERS, maxmin_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MAXMIN_PROG, MAXMIN_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, PRODUCT_PROG, PRODUCT_VERS, product_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PRODUCT_PROG, PRODUCT_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
